import { beforeEach, describe, expect, it, vi } from 'vitest'
import { mount, flushPromises } from '@vue/test-utils'
import HarvestGatewayBorrowPanel from '../HarvestGatewayBorrowPanel.vue'
import AstraGatewayRuntime from '@/components/admin/AstraGatewayRuntime.vue'
import { normalizeAstraGateway } from '@/api/admin/astraGateway'
const mocks = vi.hoisted(() => ({ get: vi.fn(), save: vi.fn(), list: vi.fn(), groups: vi.fn() }))
vi.mock('@/api/admin/astraGateway', async importOriginal => ({ ...await importOriginal<typeof import('@/api/admin/astraGateway')>(), getAstraGateway: mocks.get, saveAstraGateway: mocks.save }))
vi.mock('@/components/admin/AstraGatewayRuntime.vue', () => ({ default: { template: '<section />' } }))
vi.mock('@/components/admin/AstraGatewayHistory.vue', () => ({ default: { template: '<section />' } }))
vi.mock('@/api/admin/groups', () => ({ getAllIncludingInactive: mocks.groups }))
vi.mock('@/api/admin/accounts', () => ({ list: mocks.list }))
vi.mock('vue-i18n', async importOriginal => ({ ...await importOriginal<typeof import('vue-i18n')>(), useI18n: () => ({ t: (key: string) => key, te: () => true }) }))
vi.mock('@/components/layout/AppLayout.vue', () => ({ default: { template: '<main><slot /></main>' } }))
function value() { return { cookie_pool: { enabled: false, source_account_ids: [299], target_account_ids: [300] }, ws_session: { enabled: false, account_ids: [300] }, revision: 'one' } }
function account(id: number, groupIds: number[] = []) { return { id, name: `account-${id}`, platform: 'openai', type: 'oauth', status: 'active', group_ids: groupIds } }
function render() { return mount(HarvestGatewayBorrowPanel, { global: { stubs: { RouterLink: { template: '<a><slot /></a>' } } } }) }
beforeEach(() => {
  vi.clearAllMocks(); mocks.get.mockResolvedValue(value())
  mocks.list.mockResolvedValue({ items: [account(299, [7]), account(300, [8])], pages: 1 })
  mocks.groups.mockResolvedValue([7, 8].map(id => ({ id, name: `group-${id}`, platform: 'openai', status: 'active' })))
  mocks.save.mockImplementation(v => Promise.resolve({ ...v, revision: 'two' }))
})
describe('Astra gateway configuration', () => {
  it('shows the complete policy immediately without a collapsing control', async () => {
    const w = render()
    await flushPromises()
    expect(w.text()).toContain('admin.astraGateway.borrowTitle')
    expect(w.find('form').exists()).toBe(true)
    expect(w.find('[data-testid="expand-borrow"]').exists()).toBe(false)
    await w.get('[data-testid="cookie-toggle"]').trigger('click')
    expect(w.text()).toContain('admin.astraGateway.unsaved')
    expect(w.get('[data-testid="cookie-toggle"]').attributes('aria-checked')).toBe('true')
    expect(mocks.save).not.toHaveBeenCalled()
    w.unmount()
  })

  it('requires selected groups and persists each scheduling mode', async () => {
    mocks.get.mockResolvedValue({ ...value(), account_scheduling: true })
    const w = render(); await flushPromises()
    expect(w.get('[data-testid="scheduling-mode"]').element).toHaveProperty('value', 'account')
    await w.get('[data-testid="scheduling-mode"]').setValue('groups'); await flushPromises()
    expect(w.get('[data-testid="save"]').attributes('disabled')).toBeDefined()
    await w.get('[data-testid="scheduling-groups"] input').setValue(true)
    await w.get('form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenLastCalledWith(expect.objectContaining({ scheduling_mode: 'groups', scheduling_group_ids: [7] }))
    await w.get('[data-testid="scheduling-mode"]').setValue('model')
    await w.get('form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenLastCalledWith(expect.objectContaining({ scheduling_mode: 'model' }))
    w.unmount()
  })
  it('shows the latest three scheduling changes from runtime refresh', async () => {
    const w = render(); await flushPromises()
    expect(w.get('[data-testid="scheduling-records"]').text()).toContain('schedulingLogEmpty')
    w.findComponent(AstraGatewayRuntime).vm.$emit('scheduling', [300, 343, 344, 345].map((id, i) => ({ account_id: id, schedulable: i === 0, checked_at: '2026-09-24T12:00:00Z', reason: 'target_candy_passed' })))
    await flushPromises()
    const log = w.get('[data-testid="scheduling-records"]')
    expect(log.findAll('li')).toHaveLength(3)
    expect(log.text()).toContain('#300')
    expect(log.text()).not.toContain('#345')
    expect(log.text()).toContain('admin.astraGateway.enabled')
    expect(log.text()).toContain('admin.astraGateway.disabled')
    w.unmount()
  })
  it('defaults scheduling off and persists it without changing route settings', async () => {
    const w = render(); await flushPromises()
    const toggle = w.get('[data-testid="account-scheduling-toggle"]')
    expect(toggle.attributes('aria-checked')).toBe('false')
    await toggle.trigger('click')
    await w.get('form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenLastCalledWith(expect.objectContaining({ account_scheduling: true, cookie_pool: expect.objectContaining({ enabled: false, target_account_ids: [300] }) }))
    expect(toggle.attributes('aria-checked')).toBe('true')
    w.unmount()
  })
  it('loads disabled defaults and saves independent switches', async () => {
    const w = render(); await flushPromises()
    expect(w.get('[data-testid="cookie-toggle"]').attributes('aria-checked')).toBe('false')
    await w.get('[data-testid="cookie-toggle"]').trigger('click')
    await w.get('form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenCalledWith(expect.objectContaining({ cookie_pool: expect.objectContaining({ enabled: true }), ws_session: expect.objectContaining({ enabled: false }) }))
    expect(w.find('[role="status"]').exists()).toBe(true); w.unmount()
  })
  it('defaults IP affinity off and preserves selections when toggling and saving', async () => {
    const w = render(); await flushPromises()
    const toggle = w.get('[data-testid="ip-affinity-toggle"]')
    expect(toggle.attributes('aria-checked')).toBe('false')
    await toggle.trigger('click')
    await w.get('form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenLastCalledWith(expect.objectContaining({ cookie_pool: expect.objectContaining({ ip_affinity: true, source_account_ids: [299], target_account_ids: [300] }) }))
    expect(toggle.attributes('aria-checked')).toBe('true')
    await toggle.trigger('click')
    await w.get('form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenLastCalledWith(expect.objectContaining({ cookie_pool: expect.objectContaining({ ip_affinity: false, source_account_ids: [299], target_account_ids: [300] }) }))
    w.unmount()
  })
  it('loads saved IP affinity and retains the draft after a failed save', async () => {
    const data = normalizeAstraGateway(value()); data.cookie_pool.ip_affinity = true
    mocks.get.mockResolvedValue(data)
    const w = render(); await flushPromises()
    expect(w.get('[data-testid="ip-affinity-toggle"]').attributes('aria-checked')).toBe('true')
    mocks.save.mockRejectedValue(new Error('offline'))
    await w.get('[data-testid="ip-affinity-toggle"]').trigger('click')
    await w.get('form').trigger('submit'); await flushPromises()
    expect(w.get('[data-testid="ip-affinity-toggle"]').attributes('aria-checked')).toBe('false')
    expect(w.text()).toContain('admin.astraGateway.unsaved')
    w.unmount()
  })
  it('enables affinity with rotation, persists its budget and disables rotation when affinity is off', async () => {
    const w = render(); await flushPromises()
    expect(w.get('[data-testid="rotation-toggle"]').attributes('aria-checked')).toBe('false')
    await w.get('[data-testid="rotation-toggle"]').trigger('click')
    expect(w.get('[data-testid="ip-affinity-toggle"]').attributes('aria-checked')).toBe('true')
    await w.get('[data-testid="node-attempts"]').setValue('2')
    await w.get('[data-testid="node-cooldown"]').setValue('1800')
    await w.get('form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenLastCalledWith(expect.objectContaining({ cookie_pool: expect.objectContaining({ rotate_nodes: true, ip_affinity: true, max_node_attempts: 2, node_cooldown_seconds: 1800, source_account_ids: [299], target_account_ids: [300] }) }))
    await w.get('[data-testid="node-attempts"]').setValue('11')
    await w.get('form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenCalledTimes(1)
    await w.get('[data-testid="ip-affinity-toggle"]').trigger('click')
    expect(w.get('[data-testid="rotation-toggle"]').attributes('aria-checked')).toBe('false')
    w.unmount()
  })
  it('removes overlapping saved targets and asks for a remaining target', async () => {
    const data = value(); data.cookie_pool.enabled = true; data.cookie_pool.target_account_ids = [299]; mocks.get.mockResolvedValue(data)
    const w = render(); await flushPromises()
    expect(w.text()).toContain('admin.astraGateway.targetAccountsEmpty')
    expect(w.get('[data-testid="target-scope"]').text()).not.toContain('#299')
    await w.get('form').trigger('submit'); expect(mocks.save).not.toHaveBeenCalled(); w.unmount()
  })
  it('keeps edits on failed save and supports discard', async () => {
    mocks.save.mockRejectedValue(new Error('offline'))
    const w = render(); await flushPromises(); await w.get('[data-testid="ws-toggle"]').trigger('click')
    await w.get('form').trigger('submit'); await flushPromises()
    expect(w.text()).toContain('admin.astraGateway.saveError')
    expect(w.get('[data-testid="ws-toggle"]').attributes('aria-checked')).toBe('true')
    const discard = w.findAll('button').find(b => b.text() === 'admin.astraGateway.discard')!
    await discard.trigger('click'); await flushPromises()
    expect(w.get('[data-testid="ws-toggle"]').attributes('aria-checked')).toBe('false'); w.unmount()
  })
  it('automatically links the Cookie pool when enabling WS', async () => {
    const w = render(); await flushPromises(); await w.get('[data-testid="ws-toggle"]').trigger('click')
    await w.get('form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenCalledWith(expect.objectContaining({ cookie_pool: expect.objectContaining({ enabled: true, source_account_ids: [299], target_account_ids: [300] }), ws_session: expect.objectContaining({ enabled: true }) })); w.unmount()
  })
  it('normalizes null account arrays without sharing draft arrays', () => {
    const v = value(); const cloned = normalizeAstraGateway(v); cloned.cookie_pool.source_account_ids.push(1)
    expect(v.cookie_pool.source_account_ids).toEqual([299])
  })

  it('saves independent group selections without persisting resolved preview accounts', async () => {
    const w = render(); await flushPromises()
    await w.get('[data-testid="cookie-toggle"]').trigger('click')
    await w.get('[data-testid="source-selection"]').setValue('groups')
    await w.get('[data-testid="source-groups"] input[value="7"]').setValue(true)
    await w.get('[data-testid="target-selection"]').setValue('groups')
    await w.get('[data-testid="target-groups"] input[value="8"]').setValue(true)
    await w.get('form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenCalledWith(expect.objectContaining({ cookie_pool: expect.objectContaining({ source_selection: 'groups', source_group_ids: [7], source_account_ids: [], target_selection: 'groups', target_group_ids: [8], target_account_ids: [] }) }))
    expect(w.get('[data-testid="target-groups"] input[value="8"]').element).toHaveProperty('checked', true)
    await w.get('[data-testid="source-selection"]').setValue('accounts')
    expect(w.get('[data-testid="source-scope"] input[type="checkbox"]').element).toHaveProperty('checked', false)
    expect(w.get('[data-testid="save"]').attributes('disabled')).toBeDefined()
    w.unmount()
  })

  it('loads all account pages and excludes source members found beyond the first page', async () => {
    mocks.list.mockResolvedValueOnce({ items: [account(299, [7])], pages: 2 }).mockResolvedValueOnce({ items: [account(300, [7])], pages: 2 })
    const w = render(); await flushPromises()
    expect(mocks.list).toHaveBeenCalledTimes(2)
    expect(mocks.list.mock.calls[1][0]).toBe(2)
    await w.get('[data-testid="cookie-toggle"]').trigger('click')
    await w.get('[data-testid="source-selection"]').setValue('groups')
    await w.get('[data-testid="source-groups"] input[value="7"]').setValue(true)
    expect(w.text()).toContain('admin.astraGateway.targetAccountsEmpty')
    expect(w.get('[data-testid="target-scope"]').text()).not.toContain('#300')
    await w.get('form').trigger('submit'); expect(mocks.save).not.toHaveBeenCalled()
    w.unmount()
  })

  it('keeps a WS participant that belongs to a source group out of account targets', async () => {
    const saved = normalizeAstraGateway(value())
    Object.assign(saved.cookie_pool, { enabled: true, source_selection: 'groups', source_group_ids: [7], source_account_ids: [] })
    saved.ws_session.enabled = true; saved.ws_session.account_ids = [299]
    mocks.get.mockResolvedValue(saved)
    const w = render(); await flushPromises()
    await w.get('[data-testid="ip-affinity-toggle"]').trigger('click')
    await w.get('form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenCalledWith(expect.objectContaining({ cookie_pool: expect.objectContaining({ source_selection: 'groups', source_account_ids: [], target_selection: 'accounts', target_account_ids: [300] }), ws_session: expect.objectContaining({ account_ids: [299] }) }))
    w.unmount()
  })

  it('keeps settings editable after member loading fails and permits disabling safely', async () => {
    mocks.get.mockResolvedValue({ ...value(), cookie_pool: { ...value().cookie_pool, enabled: true }, selection_error: 'astra_group_resolution_unavailable' })
    mocks.list.mockResolvedValueOnce({ items: [account(299)], pages: 2 }).mockRejectedValueOnce(new Error('offline'))
    const w = render(); await flushPromises()
    expect(w.find('form').exists()).toBe(true)
    expect(w.get('[data-testid="selection-error"]').text()).toContain('admin.astraGateway.groupsLoadError')
    expect(w.text()).toContain('admin.astraGateway.accountsLoadError')
    await w.get('[data-testid="cookie-toggle"]').trigger('click')
    await w.get('form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenCalledWith(expect.objectContaining({ cookie_pool: expect.objectContaining({ enabled: false }) }))
    expect(mocks.save.mock.calls[0][0]).not.toHaveProperty('selection_error')
    w.unmount()
  })

  it('blocks group saves on group loading failure and recovers on refresh', async () => {
    const saved = normalizeAstraGateway(value()); saved.cookie_pool.enabled = true; saved.cookie_pool.source_selection = 'groups'; saved.cookie_pool.source_group_ids = [7]
    mocks.get.mockResolvedValue(saved); mocks.groups.mockRejectedValueOnce(new Error('offline'))
    const w = render(); await flushPromises()
    await w.get('[data-testid="ip-affinity-toggle"]').trigger('click')
    await w.get('form').trigger('submit'); expect(mocks.save).not.toHaveBeenCalled()
    expect(w.text()).toContain('admin.astraGateway.groupsLoadError')
    await w.get('[data-testid="reload"]').trigger('click'); await flushPromises()
    expect(w.get('[data-testid="source-groups"] input[value="7"]').element).toHaveProperty('checked', true)
    expect(w.findAll('[role="alert"]').some(row => row.text().includes('groupsLoadError'))).toBe(false)
    w.unmount()
  })

  it('excludes inactive groups and ineligible group members', async () => {
    mocks.groups.mockResolvedValue([{ id: 7, name: 'eligible', platform: 'openai', status: 'active' }, { id: 8, name: 'inactive', platform: 'openai', status: 'inactive' }, { id: 9, name: 'claude', platform: 'anthropic', status: 'active' }])
    mocks.list.mockResolvedValue({ items: [account(299, [7]), { ...account(301, [7]), status: 'inactive' }, { ...account(302, [7]), parent_account_id: 299 }, { ...account(303, [7]), type: 'apikey' }, account(300)], pages: 1 })
    const w = render(); await flushPromises()
    await w.get('[data-testid="source-selection"]').setValue('groups')
    const groups = w.get('[data-testid="source-groups"]')
    expect(groups.findAll('input')).toHaveLength(1)
    await groups.get('input[value="7"]').setValue(true)
    await w.get('[data-testid="cookie-toggle"]').trigger('click')
    await w.get('form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenCalledTimes(1)
    w.unmount()
  })

  it('excludes expired and malformed expiry values while keeping unbounded and future accounts', async () => {
    const now = Date.parse('2026-10-06T15:00:00Z')
    const clock = vi.spyOn(Date, 'now').mockReturnValue(now)
    mocks.list.mockResolvedValue({ items: [
      { ...account(299, [7]), expires_at: null }, account(300, [8]),
      { ...account(301, [7]), expires_at: now / 1000 + 60 },
      ...[now / 1000 - 1, now / 1000, 0, 'invalid-date', '2026-10-07T15:00:00Z', NaN, Infinity].map((expires_at, i) => ({ ...account(310 + i, [7, 8]), expires_at })),
      ...Array.from({ length: 65 }, (_, i) => ({ ...account(400 + i, [7]), expires_at: now / 1000 - 1 }))
    ], pages: 1 })
    const w = render()
    try {
      await flushPromises()
      expect(w.get('[data-testid="source-scope"]').findAll('input[type="checkbox"]')).toHaveLength(3)
      await w.get('[data-testid="source-selection"]').setValue('groups')
      await w.get('[data-testid="source-groups"] input[value="7"]').setValue(true)
      await w.get('[data-testid="target-selection"]').setValue('groups')
      await w.get('[data-testid="target-groups"] input[value="8"]').setValue(true)
      await w.get('[data-testid="cookie-toggle"]').trigger('click')
      expect(w.text()).not.toContain('admin.astraGateway.overlap')
      expect(w.text()).not.toContain('admin.astraGateway.accountLimit')
      await w.get('form').trigger('submit'); await flushPromises()
      expect(mocks.save).toHaveBeenCalledTimes(1)
    } finally { w.unmount(); clock.mockRestore() }
  })

  it.each(['astra_selection_invalid', 'astra_group_selection_invalid'])('shows a readable selection error for %s', async code => {
    mocks.get.mockResolvedValue({ ...value(), selection_error: code })
    const w = render(); await flushPromises()
    expect(w.get('[data-testid="selection-error"]').text()).toContain('admin.astraGateway.selectionInvalid')
    expect(w.get('[data-testid="selection-error"]').text()).not.toContain(code)
    expect(w.find('form').exists()).toBe(true)
    w.unmount()
  })
})
