// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/proxygroup"
)

// ProxyGroup is the model entity for the ProxyGroup schema.
type ProxyGroup struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProxyGroupQuery when eager-loading is set.
	Edges        ProxyGroupEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProxyGroupEdges holds the relations/edges for other nodes in the graph.
type ProxyGroupEdges struct {
	// Proxies holds the value of the proxies edge.
	Proxies []*Proxy `json:"proxies,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ProxiesOrErr returns the Proxies value or an error if the edge
// was not loaded in eager-loading.
func (e ProxyGroupEdges) ProxiesOrErr() ([]*Proxy, error) {
	if e.loadedTypes[0] {
		return e.Proxies, nil
	}
	return nil, &NotLoadedError{edge: "proxies"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProxyGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case proxygroup.FieldID:
			values[i] = new(sql.NullInt64)
		case proxygroup.FieldName:
			values[i] = new(sql.NullString)
		case proxygroup.FieldCreatedAt, proxygroup.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProxyGroup fields.
func (_m *ProxyGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case proxygroup.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case proxygroup.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case proxygroup.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case proxygroup.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProxyGroup.
// This includes values selected through modifiers, order, etc.
func (_m *ProxyGroup) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProxies queries the "proxies" edge of the ProxyGroup entity.
func (_m *ProxyGroup) QueryProxies() *ProxyQuery {
	return NewProxyGroupClient(_m.config).QueryProxies(_m)
}

// Update returns a builder for updating this ProxyGroup.
// Note that you need to call ProxyGroup.Unwrap() before calling this method if this ProxyGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProxyGroup) Update() *ProxyGroupUpdateOne {
	return NewProxyGroupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProxyGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProxyGroup) Unwrap() *ProxyGroup {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProxyGroup is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProxyGroup) String() string {
	var builder strings.Builder
	builder.WriteString("ProxyGroup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteByte(')')
	return builder.String()
}

// ProxyGroups is a parsable slice of ProxyGroup.
type ProxyGroups []*ProxyGroup
