// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/proxy"
	"github.com/Wei-Shaw/sub2api/ent/proxygroup"
)

// ProxyGroupUpdate is the builder for updating ProxyGroup entities.
type ProxyGroupUpdate struct {
	config
	hooks    []Hook
	mutation *ProxyGroupMutation
}

// Where appends a list predicates to the ProxyGroupUpdate builder.
func (_u *ProxyGroupUpdate) Where(ps ...predicate.ProxyGroup) *ProxyGroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyGroupUpdate) SetUpdatedAt(v time.Time) *ProxyGroupUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ProxyGroupUpdate) SetName(v string) *ProxyGroupUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProxyGroupUpdate) SetNillableName(v *string) *ProxyGroupUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// AddProxyIDs adds the "proxies" edge to the Proxy entity by IDs.
func (_u *ProxyGroupUpdate) AddProxyIDs(ids ...int64) *ProxyGroupUpdate {
	_u.mutation.AddProxyIDs(ids...)
	return _u
}

// AddProxies adds the "proxies" edges to the Proxy entity.
func (_u *ProxyGroupUpdate) AddProxies(v ...*Proxy) *ProxyGroupUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProxyIDs(ids...)
}

// Mutation returns the ProxyGroupMutation object of the builder.
func (_u *ProxyGroupUpdate) Mutation() *ProxyGroupMutation {
	return _u.mutation
}

// ClearProxies clears all "proxies" edges to the Proxy entity.
func (_u *ProxyGroupUpdate) ClearProxies() *ProxyGroupUpdate {
	_u.mutation.ClearProxies()
	return _u
}

// RemoveProxyIDs removes the "proxies" edge to Proxy entities by IDs.
func (_u *ProxyGroupUpdate) RemoveProxyIDs(ids ...int64) *ProxyGroupUpdate {
	_u.mutation.RemoveProxyIDs(ids...)
	return _u
}

// RemoveProxies removes "proxies" edges to Proxy entities.
func (_u *ProxyGroupUpdate) RemoveProxies(v ...*Proxy) *ProxyGroupUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProxyIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProxyGroupUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProxyGroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyGroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyGroupUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxygroup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyGroupUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := proxygroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProxyGroup.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxyGroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxygroup.Table, proxygroup.Columns, sqlgraph.NewFieldSpec(proxygroup.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxygroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(proxygroup.FieldName, field.TypeString, value)
	}
	if _u.mutation.ProxiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxygroup.ProxiesTable,
			Columns: []string{proxygroup.ProxiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProxiesIDs(); len(nodes) > 0 && !_u.mutation.ProxiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxygroup.ProxiesTable,
			Columns: []string{proxygroup.ProxiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProxiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxygroup.ProxiesTable,
			Columns: []string{proxygroup.ProxiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxygroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProxyGroupUpdateOne is the builder for updating a single ProxyGroup entity.
type ProxyGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProxyGroupMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyGroupUpdateOne) SetUpdatedAt(v time.Time) *ProxyGroupUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ProxyGroupUpdateOne) SetName(v string) *ProxyGroupUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProxyGroupUpdateOne) SetNillableName(v *string) *ProxyGroupUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// AddProxyIDs adds the "proxies" edge to the Proxy entity by IDs.
func (_u *ProxyGroupUpdateOne) AddProxyIDs(ids ...int64) *ProxyGroupUpdateOne {
	_u.mutation.AddProxyIDs(ids...)
	return _u
}

// AddProxies adds the "proxies" edges to the Proxy entity.
func (_u *ProxyGroupUpdateOne) AddProxies(v ...*Proxy) *ProxyGroupUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProxyIDs(ids...)
}

// Mutation returns the ProxyGroupMutation object of the builder.
func (_u *ProxyGroupUpdateOne) Mutation() *ProxyGroupMutation {
	return _u.mutation
}

// ClearProxies clears all "proxies" edges to the Proxy entity.
func (_u *ProxyGroupUpdateOne) ClearProxies() *ProxyGroupUpdateOne {
	_u.mutation.ClearProxies()
	return _u
}

// RemoveProxyIDs removes the "proxies" edge to Proxy entities by IDs.
func (_u *ProxyGroupUpdateOne) RemoveProxyIDs(ids ...int64) *ProxyGroupUpdateOne {
	_u.mutation.RemoveProxyIDs(ids...)
	return _u
}

// RemoveProxies removes "proxies" edges to Proxy entities.
func (_u *ProxyGroupUpdateOne) RemoveProxies(v ...*Proxy) *ProxyGroupUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProxyIDs(ids...)
}

// Where appends a list predicates to the ProxyGroupUpdate builder.
func (_u *ProxyGroupUpdateOne) Where(ps ...predicate.ProxyGroup) *ProxyGroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProxyGroupUpdateOne) Select(field string, fields ...string) *ProxyGroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProxyGroup entity.
func (_u *ProxyGroupUpdateOne) Save(ctx context.Context) (*ProxyGroup, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyGroupUpdateOne) SaveX(ctx context.Context) *ProxyGroup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProxyGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyGroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyGroupUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxygroup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyGroupUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := proxygroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProxyGroup.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxyGroupUpdateOne) sqlSave(ctx context.Context) (_node *ProxyGroup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxygroup.Table, proxygroup.Columns, sqlgraph.NewFieldSpec(proxygroup.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProxyGroup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, proxygroup.FieldID)
		for _, f := range fields {
			if !proxygroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != proxygroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxygroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(proxygroup.FieldName, field.TypeString, value)
	}
	if _u.mutation.ProxiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxygroup.ProxiesTable,
			Columns: []string{proxygroup.ProxiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProxiesIDs(); len(nodes) > 0 && !_u.mutation.ProxiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxygroup.ProxiesTable,
			Columns: []string{proxygroup.ProxiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProxiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxygroup.ProxiesTable,
			Columns: []string{proxygroup.ProxiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProxyGroup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxygroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
