window.PAY_PAGE_CONFIG = {
  pageEyebrow: '欢迎购买 iCode 兑换码',
  pageTitle: '充值/订阅',
  pageSubtitle: '先选充值金额，再选择可用的支付渠道。每个渠道都是独立线路，某条线路异常时可切换其他线路。',
  pageHint: '同一金额只配置一张卡，在 channels 中添加多个支付线路即可。',
  footerText: '支付完成后请按对端页面提示获取兑换码；如未到账，请保留订单信息联系客服。',
  heroBadges: ['金额清晰', '多线路可选', '移动端友好'],
  openMode: 'top',
  sections: [
    {
      title: '余额充值',
      desc: '适合稳定使用的常规充值档位。',
      tag: 'Hot',
      theme: 'orange',
      actionText: '立即购买',
      items: [
        
        {
          name: '1 元储值卡',
          desc: '体验一下可以的, 没了就不打算上了',
          tag: '捐赠',
          price: '',
          meta: '',
          url: 'https://pay.ldxp.cn/item/jzn6vw',
        },
        {
          name: '20 元储值卡',
          desc: '也就那样吧',
          tag: '捐赠',
          price: '',
          meta: '',
          url: 'https://pay.ldxp.cn/item/9hezl7',
        },
        {
          name: '10 元储值卡',
          desc: '按需选择任一支付线路完成购买。',
          tag: '常用',
          price: '¥10',
          meta: '可配置多条支付线路',
          channels: [
            {
              name: '支付线路 A',
              note: '推荐 · 稳定线路',
              url: 'https://pay.ldxp.cn/item/71m1x9',
            },
            {
              name: '支付线路 B',
              note: '备用 · 请替换为第二渠道地址',
              url: '',
            },
          ],
        },
        {
          name: '30 元储值卡',
          desc: '也就那样吧',
          tag: '捐赠',
          price: '',
          meta: '',
          url: 'https://pay.ldxp.cn/item/iquyfx',
        },
        {
          name: '50 元储值卡',
          desc: '很快就用完了',
          tag: '捐赠',
          price: '',
          meta: '',
          url: 'https://pay.ldxp.cn/item/71o2mz',
        },
        {
          name: '100 元储值卡',
          desc: '好用',
          tag: '捐赠',
          price: '',
          meta: '',
          url: 'https://pay.ldxp.cn/item/u574qv',
        },
      ],
    },
    {
      title: '日卡套餐',
      desc: '适合首次购买或测试支付兑换流程。',
      tag: 'Trial',
      theme: 'blue',
      items: [
        {
          name: '10元3日卡',
          desc: '得20元余额，需在3天内使用完',
          tag: '3日卡',
          price: '',
          meta: '充值10元得20元，有效期3天',
          url: 'https://pay.ldxp.cn/item/mw8krt',
        },
        {
          name: '30元3日卡',
          desc: '得60元余额，需在3天内使用完',
          tag: '3日卡',
          price: '',
          meta: '充值30元得60元，有效期3天',
          url: 'https://pay.ldxp.cn/item/b9g80t',
        },
      ],
    },
  ],
}
