window.PAY_PAGE_CONFIG = {
  pageEyebrow: '欢迎购买 iCode 兑换码',
  pageTitle: '充值/订阅',
  pageSubtitle: '按使用场景选择对应套餐，点击卡片后会跳转到对端充值页面。充值满10元之后联系站长加会员群。v群二维码在使用说明的金山文档中',
  pageHint: '这个页面可以直接单独打开，也可以嵌入 iframe 使用；新增板块只需要修改 sections 配置。',
  footerText: '默认会优先尝试跳转顶层窗口，避免充值页继续停留在 iframe 内。',
  heroBadges: ['官方入口', '多档套餐', '支付后兑换'],
  openMode: 'top',
  sections: [
    {
      title: '余额充值',
      desc: '适合稳定使用的常规充值档位。',
      tag: 'Hot',
      theme: 'orange',
      actionText: '立即购买',
      items: [
        
        {
          name: '1 元储值卡',
          desc: '体验一下可以的, 没了就不打算上了',
          tag: '捐赠',
          price: '',
          meta: '',
          url: 'https://pay.ldxp.cn/item/jzn6vw',
        },
        {
          name: '20 元储值卡',
          desc: '也就那样吧',
          tag: '捐赠',
          price: '',
          meta: '',
          url: 'https://pay.ldxp.cn/item/9hezl7',
        },
        {
          name: '10 元储值卡',
          desc: '也就那样吧',
          tag: '捐赠',
          price: '',
          meta: '',
          url: 'https://pay.ldxp.cn/item/71m1x9',
        },
        {
          name: '30 元储值卡',
          desc: '也就那样吧',
          tag: '捐赠',
          price: '',
          meta: '',
          url: 'https://pay.ldxp.cn/item/iquyfx',
        },
        {
          name: '50 元储值卡',
          desc: '很快就用完了',
          tag: '捐赠',
          price: '',
          meta: '',
          url: 'https://pay.ldxp.cn/item/71o2mz',
        },
        {
          name: '100 元储值卡',
          desc: '好用',
          tag: '捐赠',
          price: '',
          meta: '',
          url: 'https://pay.ldxp.cn/item/u574qv',
        },
      ],
    },
    {
      title: '日卡套餐',
      desc: '适合首次购买或测试支付兑换流程。',
      tag: 'Trial',
      theme: 'blue',
      items: [
        {
          name: '10元3日卡',
          desc: '得20元余额，需在3天内使用完',
          tag: '3日卡',
          price: '',
          meta: '充值10元得20元，有效期3天',
          url: 'https://pay.ldxp.cn/item/mw8krt',
        },
        {
          name: '30元3日卡',
          desc: '得60元余额，需在3天内使用完',
          tag: '3日卡',
          price: '',
          meta: '充值30元得60元，有效期3天',
          url: 'https://pay.ldxp.cn/item/b9g80t',
        },
      ],
    },
  ],
}
